In [1]:
###### 2.1 Tensor fundamentals ######

In [2]:
# python list
## Python lists or tuples of numbers are collections of Python objects that are individually allocated in memory
a = [1.0, 2.0, 1.0]
print('a[0]: ', a[0])
print('a[2]: ', a[2])
print('a: ', a)

a[0]:  1.0
a[2]:  1.0
a:  [1.0, 2.0, 1.0]


In [3]:
# PyTorch tensor
##  PyTorch tensors or NumPy arrays, on the other hand, are views over (typically) contiguous memory blocks 
## containing unboxed C numeric types, not Python objects. 
import torch
a = torch.ones(3)
print('tensor a: ', a)
print('tensor a[1]: ', a[1])
print('float(a[1]): ', float(a[1]))
# assign a new value
a[2] = 2.0
print('tensor a: ', a)

tensor a:  tensor([1., 1., 1.])
tensor a[1]:  tensor(1.)
float(a[1]):  1.0
tensor a:  tensor([1., 1., 2.])


In [4]:
# You can also pass a Python list to the constructor to the same effect
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0])
print('points: ', points)
float(points[0]), float(points[1])

# 2D tensor
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
print('points: ', points)
print('points.shape: ', points.shape)

# You could also use zeros or ones to initialize the tensor
points = torch.zeros(3, 2)
print('points: ', points)

# Now you can access an individual element in the tensor by using two indices
points = torch.FloatTensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
print('points[0, 1]: ', points[0, 1])
print('points[0]: ', points[0])

points:  tensor([1., 4., 2., 1., 3., 5.])
points:  tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])
points.shape:  torch.Size([3, 2])
points:  tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
points[0, 1]:  tensor(4.)
points[0]:  tensor([1., 4.])


In [5]:
###### 2.2 Tensors and storages ######

In [6]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
print('points.storage(): ', points.storage())
points_storage = points.storage()
print('points_storage[0]: ', points_storage[0])
print('points.storage()[1]: ', points.storage()[1])

# changing the value of a storage
points_storage[0] = 2.0
print('points: ', points)

points.storage():   1.0
 4.0
 2.0
 1.0
 3.0
 5.0
[torch.FloatStorage of size 6]
points_storage[0]:  1.0
points.storage()[1]:  4.0
points:  tensor([[2., 4.],
        [2., 1.],
        [3., 5.]])


In [7]:
###### 2.3 Size, storage offset, and strides ######

In [8]:
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
second_point = points[1]
print('second_point: ', second_point)
# storage offset
print('points.storage_offset: ', points.storage_offset())
print('second_point.storage_offset: ', second_point.storage_offset())
print('points[0, 1].storage_offset: ', points[0, 1].storage_offset())
# Size
print('second_point.size: ', second_point.size())
# Same as tensor.shape
print('second_point.shape: ', second_point.shape)
# stride
## stride is a tuple indicating the number of elements in the storage that have to be
## skipped when the index is increased by 1 in each dimension
print('points.stride: ', points.stride())
print('points[0, 1].stride: ', points[0, 1].stride())
## rows +1: offset 2 elements.
## cols +1: offset 1 elements.
## Accessing an element i, j in a 2D tensor results in accessing the storage_offset +
## stride[0] * i + stride[1] * j element in the storage
## For example: points[1, 0] = points.storage_offset + 1*stride[0] + 0*stride[1] = 0 + 2 + 0 = 2


second_point:  tensor([2., 1.])
points.storage_offset:  0
second_point.storage_offset:  2
points[0, 1].storage_offset:  1
second_point.size:  torch.Size([2])
second_point.shape:  torch.Size([2])
points.stride:  (2, 1)
points[0, 1].stride:  ()


In [9]:
# Changing the subtensor has a side effect on the original tensor too
second_point[0] = 10.0
print('points: ', points)
# so you can eventually clone the subtensor into a new tensor.
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
clone_second_point = points[1].clone()
clone_second_point[0] = 10.0   # Not change points.
print('points: ', points)

points:  tensor([[ 1.,  4.],
        [10.,  1.],
        [ 3.,  5.]])
points:  tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])


In [10]:
# Transpose
points = torch.tensor([[1.0, 4.0], [2.0, 1.0], [3.0, 5.0]])
points_t = points.t()
print('points_t: ', points_t)

# the two tensors share storage
id(points.storage()) == id(points_t.storage())

#  they differ only in shape and stride
print('points.shape: ', points.shape)
print('points.stride: ', points.stride())
print('points_t.shape: ', points_t.shape)
print('points_t.stride: ', points_t.stride())

# Transposing in PyTorch isn?t limited to matrices. You can transpose a multidimensional array 
# by specifying the two dimensions along which transposing.
some_tensor = torch.ones(3, 4, 5)
some_tensor_t = some_tensor.transpose(0, 2) # axis: 0 <--> 2
print('some_tensor.shape: ', some_tensor.shape)
print('some_tensor_t.shape: ',   some_tensor_t.shape)
# stride
print('some_tensor.stride: ', some_tensor.stride())
print('some_tensor_t.stride: ', some_tensor_t.stride())

# In this case, points is contiguous but its transpose is not.
print('points.is_contiguous: ', points.is_contiguous())
print('points_t.is_contiguous: ', points_t.is_contiguous())

# obtain a new contiguous tensor from a noncontiguous one 
points_t_cont = points_t.contiguous()
print('points_t_cont: ', points_t_cont)
print('points_t_cont.stide: ', points_t_cont.stride())
print('points_t_cont.storage: ', points_t_cont.storage())

points_t:  tensor([[1., 2., 3.],
        [4., 1., 5.]])
points.shape:  torch.Size([3, 2])
points.stride:  (2, 1)
points_t.shape:  torch.Size([2, 3])
points_t.stride:  (1, 2)
some_tensor.shape:  torch.Size([3, 4, 5])
some_tensor_t.shape:  torch.Size([5, 4, 3])
some_tensor.stride:  (20, 5, 1)
some_tensor_t.stride:  (1, 5, 20)
points.is_contiguous:  True
points_t.is_contiguous:  False
points_t_cont:  tensor([[1., 2., 3.],
        [4., 1., 5.]])
points_t_cont.stide:  (3, 1)
points_t_cont.storage:   1.0
 2.0
 3.0
 4.0
 1.0
 5.0
[torch.FloatStorage of size 6]


In [11]:
###### 2.4 Numeric types ######

In [12]:
#  The default data type is 32-bit floating-point.
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
print('double_points.dtype: ', double_points.dtype)
print('short_points.dtype: ', short_points.dtype)

# cast the output of a tensor-creation function to the right type by using the
# corresponding casting method.
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()
print('double_points.dtype: ', double_points.dtype)
print('short_points.dtype: ', short_points.dtype)

# or the more convenient [to] method.
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(torch.short)
print('double_points.dtype: ', double_points.dtype)
print('short_points.dtype: ', short_points.dtype)

# You can always cast a tensor of one type as a tensor of another type by using the
# type method
points = torch.randn(10, 2)
short_points = points.type(torch.short)
print('points.dtype: ', points.dtype)
print('short_points.dtype: ', short_points.dtype)

double_points.dtype:  torch.float64
short_points.dtype:  torch.int16
double_points.dtype:  torch.float64
short_points.dtype:  torch.int16
double_points.dtype:  torch.float64
short_points.dtype:  torch.int16
points.dtype:  torch.float32
short_points.dtype:  torch.int16


In [13]:
###### 2.5 Indexing tensors ######

In [14]:
# Python lists
some_list = list(range(6))
print('All elements in the list [:]: ', some_list[:])
print('From element 1 inclusive to element 4 exclusive [1:4]: ', some_list[1:4])
print('From element 1 to the end of the list [1:]: ', some_list[1:])
print('From start of the list to element 4 exclusive [:4]: ', some_list[:4])
print('From start of the list to one before the last element [:-1]: ', some_list[:-1])
print('From element 1 inclusive to element 4 exclusive in steps of 2 [1:4:2]: ', some_list[1:4:2])

# PyTorch tensors
points = torch.randn(10, 2)
print('points: \n', points)
print('All rows after first, implicitly all cloumns points[1:]: \n', points[1:])
print('All rows after first, all cloumns points[1:, :]: \n', points[1:, :])
print('All rows after first, first cloumn points[1:, 0]: \n', points[1:, 0])

All elements in the list [:]:  [0, 1, 2, 3, 4, 5]
From element 1 inclusive to element 4 exclusive [1:4]:  [1, 2, 3]
From element 1 to the end of the list [1:]:  [1, 2, 3, 4, 5]
From start of the list to element 4 exclusive [:4]:  [0, 1, 2, 3]
From start of the list to one before the last element [:-1]:  [0, 1, 2, 3, 4]
From element 1 inclusive to element 4 exclusive in steps of 2 [1:4:2]:  [1, 3]
points: 
 tensor([[-1.0562,  0.7044],
        [-0.6675, -2.2772],
        [ 1.1524, -0.8149],
        [-0.5191, -2.5744],
        [-1.2037, -0.1241],
        [-0.3604,  0.8244],
        [ 0.5563, -2.4696],
        [ 0.9884, -1.1750],
        [ 1.6692,  0.2721],
        [-2.8863,  1.2873]])
All rows after first, implicitly all cloumns points[1:]: 
 tensor([[-0.6675, -2.2772],
        [ 1.1524, -0.8149],
        [-0.5191, -2.5744],
        [-1.2037, -0.1241],
        [-0.3604,  0.8244],
        [ 0.5563, -2.4696],
        [ 0.9884, -1.1750],
        [ 1.6692,  0.2721],
        [-2.8863,  1.2873]

In [15]:
###### 2.6 NumPy interoperability ######

In [16]:
#  PyTorch tensors can be converted to NumPy arrays and vice versa efficiently
#  use buffer-sharing strategy.
points = torch.ones(3, 4)
points_np = points.numpy()
print('points_np: ', points_np)

# you can obtain a PyTorch tensor from a NumPy array this way
points = torch.from_numpy(points_np)
print('points: ', points)

points_np:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
points:  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [17]:
###### 2.7 Serializing tensors ######

In [18]:
#  PyTorch uses pickle under the hood to serialize the tensor object
points = torch.ones(3, 4)
torch.save(points, 'ourpoints.t')

# pass file descriptor.
with open('ourpoints_1.t', 'wb') as f:
    torch.save(points, f)
    
# Loading your points back
points = torch.load('ourpoints.t')
print('points: ', points)
# with file descriptor
with open('ourpoints_1.t', 'rb') as f:
    points = torch.load(f)
print('points: ', points)

points:  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
points:  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [19]:
# HDF5 is a portable, widely supported format for representing serialized multidimensional arrays, 
# organized in a nested key-value dictionary
# sudo apt install python3-h5py 
import h5py
points = torch.ones(3, 4)

# write
f = h5py.File('outpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

# read
f = h5py.File('outpoints.hdf5', 'r')
dset = f['coords']
print('Read points: ', dset[:])

# to tensor
points_tensor = torch.from_numpy(dset[:])
print('pints_tensor: ', points_tensor)
f.close()

Read points:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
pints_tensor:  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


/usr/lib/python3/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [ ]:
###### 2.8 Moving tensors to the GPU ######

In [24]:
points_gpu = torch.tensor([[1, 4], [2, 1], [3, 4]], device='cuda')

# copy a tensor created on the CPU to the GPU
points = torch.ones(3, 4)
points_gpu = points.to(device='cuda')

# your machine has more than one GPU
points_gpu = points.to(device='cuda:0')

# Multiplication performed on the CPU
points = 2*points
# Multiplication performed on the GPU
points_gpu = 2*points.to(device='cuda')
print('points: ', points)
print('points_gpu: ', points_gpu)

# use the shorthand methods cpu and cuda instead of the `to` method.
points_gpu = points.cuda()  # cpu to gpu
points_gpu = points.cuda(0) # cpu to gpu 0
points_cpu = points_gpu.cpu() # gpu to cpu

points:  tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])
points_gpu:  tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]], device='cuda:0')


In [ ]:
###### 2.9 The tensor API ######

In [26]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)
a_t = a.transpose(0, 1)
print('a: ', a)
print('a_t: ', a_t)

a:  tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
a_t:  tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [28]:
# operates in-place.
a = torch.ones(3, 2)
a.zero_() # operate in-place
print('a: ', a)

a:  tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [ ]:
###### Exercises ######

In [33]:
# 1. Create a tensor a from list(range(9)). Predict then check what the size, offset, and strides are.
a = torch.tensor(list(range(9)))
print('a: ', points)
print('a.size: ', a.size())
print('a.offset: ', a.storage_offset())
print('a.stride: ', a.stride())


a:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
a.size:  torch.Size([9])
a.offset:  0
a.stride:  (1,)


In [35]:
# 2. Create a tensor b = a.view(3, 3). What is the value of b[1,1]?
a = torch.ones(3, 2)
# torhc.tensor.view: Returns a new tensor with the same data as the self tensor but of a different shape
b = points.view(3, 3) # reshape
print('b: ', b)
print('b[1, 1]: ', b[1, 1])

b:  tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
b[1, 1]:  tensor(4)


In [37]:
# 3. Create a tensor c = b[1:,1:]. Predict then check what the size, offset, and strides are.
c = b[1:, 1:]  # From first rows, first cloumns.
print('c: ', c)
print('c.size: ', c.size())
print('c.offset: ', c.storage_offset())
print('c.stride: ', c.stride())

c:  tensor([[4, 5],
        [7, 8]])
c.size:  torch.Size([2, 2])
c.offset:  4
c.stride:  (3, 1)


In [45]:
# 4. Pick a mathematical operation like cosine or square root. 
# Can you find a corresponding function in the torch library?

# https://pytorch.org/docs/master/torch.html#math-operations
points = torch.randn(3, 3)
# points = torch.ones(3, 3)
print('points: ', points)
# cos_pts = torch.cos(points)
print('cos: ', torch.cos(points))
print('sqrt: ', torch.sqrt(points))

points:  tensor([[-0.9961,  0.0561, -0.9141],
        [-1.3874, -0.8220, -0.7249],
        [ 1.2126, -1.0802, -1.1914]])
cos:  tensor([[0.5436, 0.9984, 0.6105],
        [0.1824, 0.6807, 0.7486],
        [0.3506, 0.4712, 0.3704]])
sqrt:  tensor([[   nan, 0.2368,    nan],
        [   nan,    nan,    nan],
        [1.1012,    nan,    nan]])
